In [1]:
import numpy as np
import os
import cv2
import keras
import matplotlib.pyplot as plt
from imutils import paths
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img

Using TensorFlow backend.


In [2]:
classes = ['c0', 'c1','c2','c3','c4','c5','c6','c7','c8','c9']
Dict = {'c0' : 0, 'c1' :1, 'c2':2, 'c3':3, 'c4':4,'c5':5,'c6':6,'c7':7,'c8':8,'c9':9}
images = []
Img_labels = []
train_path='imgs/train'

In [3]:
for label in classes:
      path = os.path.join(train_path , label)
      for img in os.listdir(path):
         img = cv2.imread(os.path.join(path,img))
         new_img = cv2.resize(img, (64, 64))
         images.append(new_img)
         Img_labels.append(Dict[label])
         # print(images,Img_labels)
     #print(label)

In [4]:
img=np.array(images)
labels=np.array(Img_labels)
print(img.shape)

(22424, 64, 64, 3)


In [22]:
# applying color histogram using function for all the images
def color_hist(img):
    histograms = []
    hist=0
    for i in img:
        hist=cv2.calcHist([i], [0,1,2],None, [6,6,6], [0, 256, 0, 256, 0, 256])
        histograms.append(hist.flatten())
        #To compute the histogram for all three red, green, and blue channels we have taken[0,1,2] and for gray scale we have to take [0]
    result = np.array(histograms)
    print(result)
color_hist(img)

[[ 957.   22.    0. ...  172.  128.  149.]
 [1163.   23.    0. ...   22.  120.  660.]
 [1060.    4.    0. ...   38.  159.  656.]
 ...
 [1148.    7.    0. ...   98.  152.  418.]
 [1194.    9.    0. ...  234.  103.   80.]
 [ 872.   14.    0. ...  193.  293.  206.]]
